#!/bin/bash
#
# chkconfig: 35 90 12
# description: rememberd server
#

# Get function from functions library
. /etc/init.d/functions

start() {
      initlog -c "echo -n Starting rememberd server: "
      /home/ubuntu/.cargo/bin/cargo run --release --manifest-path /home/ubuntu/rememberd/Cargo.toml &
      ### Create the lock file ###
      touch /var/lock/subsys/rememberd
      success $"rememberd server startup"
      echo
}

stop() {
      initlog -c "echo -n Stopping rememberd server: "
      killproc rememberd
      ### Now, delete the lock file ###
      rm -f /var/lock/subsys/rememberd
      echo
}

### main logic ###
case "$1" in
      start)
            start
            ;;
      stop)
            stop
            ;;
      status)
            status rememberd
            ;;
      restart|reload|condrestart)
            stop
            start
            ;;
      *)
            echo $"Usage: $0 {start|stop|restart|reload|status}"
            exit 1
esac

exit 0